### ISSUE TITLE
Case count displayed in inventory

### ISSUE THREAD

**Issue by justinazhang** [CalNourish/pantry-webapp#168]
<img width="1074" alt="Screen Shot 2023-04-05 at 3 39 39 PM" src="https://user-images.githubusercontent.com/36006871/230227242-bf47571e-642e-4391-b2b8-673c1a0d9759.png">
There was a request to display case count in the inventory page and I think we could probably just put it right next to the individual count in parenthesis or something like that

**Comment by tinyherocarrot** [comment]
@justinazhang 
- Should "Case Count" column be sort-able?
- Is a new "Case Count" col acceptable solution? Or does it need to be in parentheses next to "Count" value? [see attached]
<img width="1413" alt="Screen Shot 2023-05-17 at 9 43 48 AM" src="https://github.com/CalNourish/pantry-webapp/assets/26530752/d6a1cde7-2f20-43a7-a20b-77ffdf6c28c3">

**Comment by justinazhang** [comment]
> @justinazhang
> 
> * Should "Case Count" column be sort-able?
> * Is a new "Case Count" col acceptable solution? Or does it need to be in parentheses next to "Count" value? [see attached]
> 
> <img alt="Screen Shot 2023-05-17 at 9 43 48 AM" width="1413" src="https://user-images.githubusercontent.com/26530752/239021435-d6a1cde7-2f20-43a7-a20b-77ffdf6c28c3.png">

- Should "Case Count" column be sort-able?
It'd be nice to have it sortable be definitely not necessary
- Is a new "Case Count" col acceptable solution? 
This looks good! I think the main thing is just not storing it as an attribute in firebase and only displaying it locally on the page
