### ISSUE TITLE
Format verification checkin 

### ISSUE THREAD

**Issue by justinazhang** [CalNourish/pantry-webapp#178]
Add some format verification to student ids before writing them to the spreadsheet on the checkin

**Comment by tinyherocarrot** [comment]
@justinazhang can you please provide parameters of valid student ids?

**Comment by tinyherocarrot** [comment]
From Natalia: 

> CAL ID INFO

Student ID#s are 10-digit student ID number beginning with 30 or an 8-digit ID number beginning with either a 1, 2, 7, or 8.

Employees or affiliates 8-digit ID number beginning with 01 or an 8-digit UCPath ID number that begins with 10.

**Comment by janiseliang** [comment]
Our Cal ID scanner gives encrypted IDs in the form of 810:dddddddd, so the IDs will be a mix of this and the 30dddddddd format (if manually typed). Also we use the ID "1" in cases where the visitor is a general community member that does not have an ID.
