### ISSUE TITLE
Writing to Check In Google Sheet is broken

### ISSUE THREAD

**Issue by tinyherocarrot** [CalNourish/pantry-webapp#190]
_Submitted by: Natalia Semeraro_

# Summary
"Check in" page is not writing to newly created Google Sheet "[Core] Food Pantry (AY 23-24)".

- Old sheet: https://docs.google.com/spreadsheets/d/1QDyC7uyM51JavfPHfmoY4DTBo3PoOAoN9CJwA4jhLuY/edit#gid=1020810174
- Test sheet: https://docs.google.com/spreadsheets/d/1nbyEAd4P5DpgO_UrB6JBdjXHkYGxV4WtEhm8Mhg4aLY/edit#gid=363387482
- New sheet: https://docs.google.com/spreadsheets/d/10YGY81alIOArlr52JKdHlpEbg9ez0XqTEl7VQt7oEJI/edit#gid=1432734829

## Steps to reproduce the bug

1. Navigate to `https://www.ucbbncfp.com/admin`
2. Update the "Check In" Google Sheet ID to `10YGY81alIOArlr52JKdHlpEbg9ez0XqTEl7VQt7oEJI`
3. Navigate to `https://www.ucbbncfp.com/checkin`
4. Type "1" into Cal ID field
5. Submit (Enter)

## Expected result

"Successfully Logged ID: 1" feedback message and see new entry in Gsheet

## Actual Result

See error in Inspect > Network:

> POST | https://www.ucbbncfp.com/api/admin/WriteCheckIn `500 Internal Service Error`:
> "error: error writing to Pantry data sheet: Error: You are trying to edit a protected cell or object. Please contact the spreadsheet owner to remove protection if you need to edit."

**Comment by tinyherocarrot** [comment]
_Update 12 July 2023 2:32PM_

After doing a bit of testing, it seems to me like the issue may be with access to the newly created Google sheet. Using the ID to the old sheet or the test sheet, checking in works with no errors. 

Old sheet: https://docs.google.com/spreadsheets/d/1QDyC7uyM51JavfPHfmoY4DTBo3PoOAoN9CJwA4jhLuY/edit#gid=1020810174
Test sheet: https://docs.google.com/spreadsheets/d/1nbyEAd4P5DpgO_UrB6JBdjXHkYGxV4WtEhm8Mhg4aLY/edit#gid=363387482
New sheet: https://docs.google.com/spreadsheets/d/10YGY81alIOArlr52JKdHlpEbg9ez0XqTEl7VQt7oEJI/edit#gid=1432734829

**Comment by nataliagilsem** [comment]
We fixed this! We had to add access to the sheet directly in addition to the full spreadsheet. It also was skipping over cells that had things written in the columns next to it so once it had access the bot was writing to the bottom
